config/routes.rb
Rails.application.routes.draw do
  root "artists#index"
  resources :artists, only: [:index, :show] do
    resources :songs
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
  end
  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy
    redirect_to artists_path
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:edit, :update]
  def index
    @artist = Artist.find(params[:artist_id])
    @songs = @artist.songs
     @song =Song.new
  end
  def show
   end

   def set_song
    @song = Song.find(params[:id])
  end
  def new

     @song =Song.new

   end
   def create
     @artist = Artist.find(params[:artist_id])
     @song = @artist.songs.create(song_param)


     respond_to do |format|
         if @song.save
           format.html { redirect_to artist_songs_path(@artist.id) , notice: 'Song was successfully created.'}
           format.json { render :show, status: :created, location: @song }
         else
           format.html { redirect_to ([@artist, @song]) }
           format.json { render json: @song.errors, status: :unprocessable_entity }
         end
       end
  end

  private
  def song_param
    params
      .require(:song)
      .permit(
        :title, :song_url
      )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/index.html.erb
<h1>Artists</h1>
<% @artists.each do |artist| %>
<p><%= link_to artist.name, artist_path(artist.id) %></p>
<% end %>

app/views/artists/show.html.erb
<h1><%=@artist.name%></h1>
<p>Image: <%=@artist.remote_image_url%></p>
<hr>
<%=link_to "[see songs]", artist_songs_path(@artist.id)%>

<%=link_to "[Delete]", artist_path(@artist.id), method: :delete,  data: {confirm: "Are you sure?"}%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodaissuerifyN</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
  <%= yield %>
</div>

  </body>
</html>

app/views/songs/_form.html.erb
<%= form_for([@artist, @song]) do |f| %>
  <div class="form-group <%= song.errors.any? ? 'has-error' : '' %>"
    id="formgroup-title">
    <%= f.text_field :title, placeholder: "Enter song", class: 'form-control' %>

    <% if song.errors.any? %>
      <% song.errors.full_messages.each do |message| %>
        <span class="help-block"><%= message %></span>
      <% end %>

    <% end %>
  </div>

<% end %>

app/views/songs/_song.html.erb
<tr class="song <%= song.title? ? "success" : "" %>" data-id="<%= song.id %>">
  <td>
    <input name="song[<%= song.id %>]" id="song-<%= song.id %>" type="checkbox" value="" >
  </td>
  <td>
    <label for="song-<%= song.id %>"><%= song.title %></label>
  </td>
</tr>

app/views/songs/index.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="page-header">SongList</h1>

    <% if notice.present? %>
      <div class="alert alert-info" role="alert">
        <%= notice %>
      </div>
    <% end %>

    <%= render "form", song: @song %>

    <hr />

    <table class="table table-striped" id="songList">
      <%= render @songs %>
    </table>

    <div class="footer">
      <a href="" id="Delete", onclick="deleteSong();">Delete</a>
      <a href="" id="Delete-all">Delete-all</a>
    </div>
  </div>
</div>

<p><%=link_to "[back to]", artist_path(@artist.id)%></p>

app/views/songs/show.html.erb
<!-- <% @songs.each do |song| %>

<p><%=song.title%></p>
<p><%=song.song_url%></p>
<%end%> -->